### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by thrypuro** [thrypuro/thrypuro.github.io#1]
- [ ] Add Cyberapocylpse writeups
- [ ] Add pwnEd 5 author challenge writeups
- [ ] Blogpost about generating golden sun passwords
